### ISSUE TITLE
Changes on index.html

### ISSUE THREAD

**Issue by robertbahn** [SpacehuhnTech/esp8266_deauther#1142]
Hello, is it possible to make changes to the index.html? I put >bool webSpiffs on true,  edited the index.html.gz and uploaded it via ESP8266 Sketch Uploader. No changes have been made... Can you help me?

**Comment by SnAckXy** [comment]
i got the same problem every thing i want/try to change do nothing even after uploading it 100 times with no error´s ore stuff like that even smale things like ssid name ....
