### ISSUE TITLE
pwned authentication error

### ISSUE THREAD

**Issue by danyboy1972** [SpacehuhnTech/esp8266_deauther#1175]
i flashed my wemos, plugged it into a usb cable and get the pwned SSID but when i type the password i get 'authentication error' does anyone have any ideas whats wrong?
cheers.

**Comment by Jacob12138xieyuan** [comment]
what is the password?

**Comment by danyboy1972** [comment]
hello,
the password is deauther.


________________________________

**Comment by spectrapulse** [comment]
I've tried using the password "deauther" but it refuses to authenticate. Even after reflashing it refuses to do so.

**Comment by forseenink3238** [comment]
Are you doing this on a laptop.

**Comment by spectrapulse** [comment]
Yes...

**Comment by forseenink3238** [comment]
Try to connect to pwned using a phone, this time there shouldn't be any authentication problem.

**Comment by spectrapulse** [comment]
I already tried that but the same thing happens on my phone. I've tried using multiple Android powered phones and an iPhone of a friend.

**Comment by mmuyakwa** [comment]
If you changed the password (in code or on the websites settings) and it is shorter than 8 characters, you won't be able to log in anymore.
It is highlighted nowhere which is unfortunate.
