### ISSUE TITLE
The diode on the board flashes every 5 seconds.

### ISSUE THREAD

**Issue by 88cretin88** [SpacehuhnTech/esp8266_deauther#1177]
Hello, there is a problem. The firmware of the ESP8266 CH340G module is running, it works correctly, but the next day the board starts to flash every 5 seconds and WiFi does not work. If there may be a problem.

**Comment by tobozo** [comment]
Hello, what do you get in the Serial output? Have you tried erasing the flash and flashing it again?

![image](https://user-images.githubusercontent.com/1893754/68748063-0ca10c80-05fc-11ea-9c1e-6f76bb8e9bff.png)

**Comment by 88cretin88** [comment]
After flashing everything works fine, it stops working the next day. I don’t know why this happens.

**Comment by altimmons** [comment]
That’s roughly the time it would take for the micros register to overflow and reset. If someone were using that it could be a cause.
