### ISSUE TITLE
Broken link on Github  for deauther_2.1.0_DSTIKE_OLED_v3.5_Monster.bin

### ISSUE THREAD

**Issue by Gittyup1000** [SpacehuhnTech/esp8266_deauther#1181]
Hello can someone fix the broken download link for the following bin file?

**https://github.com/spacehuhn/esp8266_deauther/releases/download/v2.1.0/deauther_2.1.0_DSTIKE_OLED_v3.5_Monster.bin**

Found on page.
https://github.com/spacehuhn/esp8266_deauther/releases

**Comment by r0073rr0r** [comment]
You can find this link on the bottom of the page in Assets section:
https://prnt.sc/pzi4ir

Click there instead until someone fix.

**Comment by spacehuhn** [comment]
Fixed link is https://github.com/spacehuhn/esp8266_deauther/releases/download/v2.1.0/deauther_2.1.0_DSTIKE_OLED_v3.5_v4_Monster.bin
