### ISSUE TITLE
Uploaded deauther using arduino to watch

### ISSUE THREAD

**Issue by chaserit123** [SpacehuhnTech/esp8266_deauther#1183]
I used the arsuino project and uploaded to my deauther watch and now the display no longer works?

**Comment by beckerichmika** [comment]
Did you select the right board type? Read carefully point 3 on here:https://github.com/spacehuhn/esp8266_deauther/wiki/Installation#compiling-using-arduino-ide to make sure you select the deauth one

**Comment by wei2374** [comment]
I have a similar problem, I have configured everything as the tutorial said, also the config.h file is already changed for wristband, but still after a successful flash there is no display on the screen.

**Comment by gorkalombar** [comment]
Same happend to me! I bought it like 1 month ago, and as soon as I opened it an switched on, leds are working but nothing is shown on display! I tried flashing 3 different .bin files with the N2D, but none of them is working.
Please, help!!!

**Comment by DangerousPony204** [comment]
just go into your boards network 'pwned' and check enable display again under settings, works for me everytime
