### ISSUE TITLE
Screen unresponsive constant red light 

### ISSUE THREAD

**Issue by AzzA1991** [SpacehuhnTech/esp8266_deauther#1184]
![15751173366223132644711812820331](https://user-images.githubusercontent.com/58362394/69900640-edc9a680-136d-11ea-8e05-856bd608622f.jpg)
![15751173542773857469899658610335](https://user-images.githubusercontent.com/58362394/69900645-f8843b80-136d-11ea-81bd-f5e1990d1abf.jpg)

**Comment by tobozo** [comment]
screen doesn't look broken
what does the serial output say ?

**Comment by spacehuhn** [comment]
Try connecting to 'pwned' and check `enable display` under settings
