### ISSUE TITLE
esp32?

### ISSUE THREAD

**Issue by 0x77dev** [SpacehuhnTech/esp8266_deauther#1187]
Maybe some esp32 support?

**Comment by orgixmh** [comment]
It is not possible yet, esp32 wifi library rejects deauth packets with error:  "wifi: unsupport frame type: 0a0".

**Comment by cynay** [comment]
Should be possible now with this: https://github.com/Jeija/esp32-80211-tx

**Comment by jLynx** [comment]
https://github.com/spacehuhn/esp8266_deauther/wiki/FAQ#esp32-and-esp8285-support

**Comment by spacehuhn** [comment]
Hi! There are many issues on this repo about ESP32 support, so I published a blog post to bring some clarity to this topic: https://blog.spacehuhn.com/esp32-deauther/ 
TL;DR: It's made for the ESP8266, and I have no plans to port this application to the ESP32. But it's open-source, so you're free to do it yourself if you want. I appreciate your understanding.
