### ISSUE TITLE
Nodemcu not detected after flashing esp8266_deauther

### ISSUE THREAD

**Issue by Raidr1212** [SpacehuhnTech/esp8266_deauther#1189]
I have flashed the latest version of the deauther and it works perfectly. The only problem is my computer no longer recognizes the nodemcu I even tried to put it into flash mode but and it goes into flash mode(The blue led only blinks once and no more) but my computer still wont recognize it
![image](https://user-images.githubusercontent.com/42038992/70639912-3590dd80-1c4c-11ea-82f5-294e7783c15e.png) 
I am unable to flash anything else.
My nodemcu has a square chip.
#951

**Comment by itsmemohit** [comment]
Connect your node mcu which is not being recognized by Windows. You will see an Unknown USB device ( Device Descriptor Request Failed) with the yellow sign in Universal Serial Bus controllers. Now right-click on it and click Uninstall to remove them. Restart your PC and the drivers will be automatically installed
it  worked for me

**Comment by Raidr1212** [comment]
> Connect your node mcu which is not being recognized by Windows. You will see an Unknown USB device ( Device Descriptor Request Failed) with the yellow sign in Universal Serial Bus controllers. Now right-click on it and click Uninstall to remove them. Restart your PC and the drivers will be automatically installed
> it worked for me

That sadly has not worked for me
