### ISSUE TITLE
stop attack from serial input

### ISSUE THREAD

**Issue by dave0111** [SpacehuhnTech/esp8266_deauther#1194]
i wanted to know if there is any way of stopping an attack by sending a serial command other than attack timeout

**Comment by unguest** [comment]
You can connect to a GPIO/Serial port (it depends what device you are using) and then code that yourself. It should looks like something like that : 

```C
#define atkPort 8 // Just taking arbitrary values in the whole program, adapt to your needs

void setup() {
      [your setup function here]
      pinMode(atkPort, INPUT);
}

void loop() {
     [your loop function here]
     if(digitalRead(atkPort) == LOW) {
          // TODO : stop attack
     }
}
```

**Comment by robin-weaver** [comment]
If you are controlling via serial UART and sending commands, why can't you simply type `stop`?
