### ISSUE TITLE
v2.1.4-easter , how esp8266 - esp32 work?

### ISSUE THREAD

**Issue by Neodim7** [SpacehuhnTech/esp8266_deauther#1214]
hello

in  release v2.1.4-easter i see this - ESP32 Support : wire the rx/tx of your ESP8266_deauther to the rx/tx of an ESP32 and enjoy the benefits of serial tunneling!

but what firmware i must will flash to esp32?

thank you

**Comment by tobozo** [comment]
you're a month and half early, please come back on April 1st :smile:

**Comment by Neodim7** [comment]
i connected it and tryed )) and ... nothing happen... ok i will try it at 1 april ))

**Comment by tobozo** [comment]
Actually that's more a way to build your own deauther than an easter egg.

The joke is about the uselessness of doing it, why would you do serial tunneling in the first place?

See [this project](https://github.com/tobozo/M5Stack-ESP12-Shield) as an example of how useless it can be :-)

**Comment by Neodim7** [comment]
Mmm, maybe for better heat dissipation :)
