### ISSUE TITLE
Problem uploading code to the ESP8266 !

### ISSUE THREAD

**Issue by lqkqqq** [SpacehuhnTech/esp8266_deauther#1219]
I cannot upload the code to the board because :
SH1106Wire.h: No such file or directory
SSD1306Wire.h: No such file or directory
SH1106Spi.h: No such file or directory
SSD1306Spi.h: No such file or directory

**Comment by unguest** [comment]
You have to install the librairies. Nonetheless, I think it would be better to flash an already-existing binary rather than compiling your own one (if you don't require too, of course).
https://github.com/SpacehuhnTech/esp8266_deauther/releases should be the place for it :)
