### ISSUE TITLE
selcting the ap and start attack not working.

### ISSUE THREAD

**Issue by Alpha-1729** [SpacehuhnTech/esp8266_deauther#1232]
i select the target ap.
and click on the start attact.
but all device can connect to the ap.

**Comment by richrd** [comment]
Are the devices connecting on the 2Ghz or 5Ghz band? If they're on 5Ghz it wont work because 5Ghz isn't supported on the ESP 8266.

**Comment by Alpha-1729** [comment]
i tried it using my laptop as ap and tablet as client..
not working

**Comment by richrd** [comment]
Did you check which band they're on?

**Comment by Alpha-1729** [comment]
i didnt't know what you mean.

**Comment by richrd** [comment]
This explains what the bands are https://www.howtogeek.com/222249/whats-the-difference-between-2.4-ghz-and-5-ghz-wi-fi-and-which-should-you-use/

**Comment by Alpha-1729** [comment]
they are on 2.5ghz

**Comment by spacehuhn** [comment]
Have you tried it on other networks?

**Comment by Alpha-1729** [comment]
> Have you tried it on other networks?

yes , but client device can connect to the AP
