### ISSUE TITLE
bricked my deauther watch v2 while messing with Arduino software. Anyone got the source code?

### ISSUE THREAD

**Issue by petrolhead773** [SpacehuhnTech/esp8266_deauther#1235]
bricked my deauther watch v2 while messing with Arduino software. Anyone got the source code? I couldn't find it on this github or Dstike website.

When I try to turn it on the screen and led stays blank as if it's off.

**Comment by unguest** [comment]
You don't need the source code, you have binaries that you can flash. You may get some info about what chip your watch is using and then select the good binary there : https://github.com/SpacehuhnTech/esp8266_deauther/releases

**Comment by spacehuhn** [comment]
By the way, the source code is also literally right here: https://github.com/SpacehuhnTech/esp8266_deauther
