### ISSUE TITLE
Error: exec: "{runtime.tools.esptool.path}/esptool.exe": file does not exist

### ISSUE THREAD

**Issue by Derranfold29** [SpacehuhnTech/esp8266_deauther#1236]
Dear Ladies and Gentlemen

While I've followed all the instructions (esp8266 deauther board selected, added libraries etc) I receive now the following error message

`exec: "{runtime.tools.esptool.path}/esptool.exe": file does not exist`

I've tried so many things, but seems like I can't fix it

Edit: Oh and I'm using the AZDelivery NodeMCU Lua Amica Modul V2 ESP8266 ESP-12F WIFI Wifi Development Board with CP2102 and choosed the Board "Generice ESP8266" from the ESP Deauther Modules

I've flashed the default bin "Default Config (NodeMCU, Wemos d1 mini, ...)" with Node2Deauther

**Comment by spacehuhn** [comment]
Does this issue maybe help: https://github.com/SpacehuhnTech/esp8266_deauther/issues/740
