### ISSUE TITLE
Need Help Resetting Password

### ISSUE THREAD

**Issue by GhostSecurity3827** [SpacehuhnTech/esp8266_deauther#1311]
> Have you searched for existing (open and closed) issues describing the same problem?
I don't know how to reset the admin password

Yes/No

**Describe the error**
A clear and concise description of what the problem is.
What do you think causes it?

```
Error/Compile/Output Log
```

**To Reproduce**

**Expected behavior**

**Screenshots**

**Environment (please complete the following information):**
 - Version [e.g. 1.0]
 - Hardware [e.g. DSTIKE, DIY]

**Attempts**
What have you already tried and didn't work out.

**Additional context**
Provide as much information as possible, better too much than too little!
If you don't use this template, your issue might be closed and tagged invalid!

**Comment by AleksZavg** [comment]
Go this https://github.com/SpacehuhnTech/esp8266_deauther/wiki/FAQ#how-to-do-a-reset
