### ISSUE TITLE
Có hỗ trợ cho esp32 không ạ

### ISSUE THREAD

**Issue by tienanh996tn** [SpacehuhnTech/esp8266_deauther#1344]
> Please search for existing (open and closed) issues first to avoid duplicates.  
Also have a look at the [Wiki](https://github.com/spacehuhntech/esp8266_deauther/wiki).

**Comment by vuongfcc** [comment]
Không hỗ trợ esp32, ông có thắc mắc gì thì bấm vào mục issues tìm trước đã. Nếu trong mục issees không có, thì mở chủ đề để hỏi. Mà đã lên đây hỏi thì viết bằng tiếng Anh. Không biết tiếng tiếng anh thì dùng Google dịch để dịch sang tiếng anh rồi hãy đăng lên đây.
Đừng có như thằng trẻ trâu, cứ hở tí là hỏi vớ vẩn. Dùng não đi!

**Comment by 244v234** [comment]
Qua đây tôi hỗ trợ cho https://github.com/244v234/ESP8266-WifiPhisher
