### ISSUE TITLE
Evil Twin its feature should come urgently 

### ISSUE THREAD

**Issue by keko01** [SpacehuhnTech/esp8266_deauther#1436]
The evil twin method should be added urgently

**Comment by JackWilder00** [comment]
Is there a possibility to create an evil twin attack?

**Comment by ngocthuong234** [comment]
With only one esp8266, deauth + evil twin + Facebook, Google, Twitter,..
https://youtu.be/oKsRb4KXXk0
https://youtu.be/Nt-0aTfPECQ
