### ISSUE TITLE
Adding Haptic (Vibration) Feedback to OLED version...

### ISSUE THREAD

**Issue by shreyask21** [SpacehuhnTech/esp8266_deauther#647]
I want to add vibration feedback to the ESP whenever a button is pressed just like in smartphones... I want to use the vibration motor used in mobile phones...

![Vibrator Motor](https://user-images.githubusercontent.com/30172640/32107385-0ba68ae6-bb4c-11e7-965e-4850538675f2.jpg)

> The basic Circuit Idea is:-

![circuit](https://user-images.githubusercontent.com/30172640/32107555-97906932-bb4c-11e7-9ed6-47785943ec9b.JPG)

> My Deauther Board(DIY):-

![img_20171027_192959](https://user-images.githubusercontent.com/30172640/32107916-a8a59782-bb4d-11e7-8917-035fc5ff6cc2.jpg)
![img_20171027_192827](https://user-images.githubusercontent.com/30172640/32107917-a8d91602-bb4d-11e7-82bc-0a55a6880bd0.jpg)
![img_20171027_192846](https://user-images.githubusercontent.com/30172640/32107918-a90b72c8-bb4d-11e7-8f59-0415127e4242.jpg)
![img_20171027_192853](https://user-images.githubusercontent.com/30172640/32107919-a93ee658-bb4d-11e7-9f7a-46581b5a9d1a.jpg)

> Some Info:-

1. Board: **NodeMCU Amica**
2. Using OLED: **YES**
3. Using WebServer: **YES**
4. Using Serial: **NO**
5. Installation mode: **Source**
6. Code/binary version: **1.6**
7. Flash size:  **1M**
8. Flash method: **Arduino IDE**
9. Flash Frequency: **40Mhz**
10. Upload Speed: **115200**
11. Powered by:  **Power Bank**

**Comment by cicemon212** [comment]
Hello, i made something very similar to you and a like to add a haptic feed when a press ok. I should try. This. I used a rotatory encoder to move on menu fields. 
![20180213_072353](https://user-images.githubusercontent.com/36436251/36137435-85c4e144-1095-11e8-9f03-17cd7ddbaf1d.jpg)
